# Generated by Django 5.1.4 on 2025-02-21 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_group_user'),
    ]

    operations = [
    ]
