# Generated by Django 5.1.4 on 2025-02-27 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_auto_20250221_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='background_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='link',
            name='link_type',
            field=models.CharField(choices=[('solid', 'Solid'), ('outline', 'Outline'), ('transparent', 'Transparent')], default='solid', max_length=20),
        ),
        migrations.AddField(
            model_name='link',
            name='shape',
            field=models.CharField(choices=[('square', 'Square'), ('rounded', 'Rounded'), ('pill', 'Pill')], default='square', max_length=20),
        ),
        migrations.AddField(
            model_name='link',
            name='text_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
