# Generated by Django 5.1.4 on 2025-02-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_remove_link_background_color_remove_link_link_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='link',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
